name: Deploy to WordPress.org

on:
  release:
    types: [ released, prereleased ]
  workflow_dispatch:

jobs:
  deploy_to_wp_repository:
    name: WordPress.org deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          composer install --no-dev
          npm install
          npm run build

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
